/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
  };
  blocks: {};
  collections: {
    programs: Program;
    cohorts: Cohort;
    startups: Startup;
    founders: Founder;
    mentors: Mentor;
    partners: Partner;
    events: Event;
    resources: Resource;
    articles: Article;
    infrastructure: Infrastructure;
    testimonials: Testimonial;
    faqs: Faq;
    metrics: Metric;
    media: Media;
    staff: Staff;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    cohorts: CohortsSelect<false> | CohortsSelect<true>;
    startups: StartupsSelect<false> | StartupsSelect<true>;
    founders: FoundersSelect<false> | FoundersSelect<true>;
    mentors: MentorsSelect<false> | MentorsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    infrastructure: InfrastructureSelect<false> | InfrastructureSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    metrics: MetricsSelect<false> | MetricsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Structured paths from idea to venture.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  /**
   * One line. What this program does, in plain words.
   */
  tagline: string;
  /**
   * First section on the page. Who should apply — and who should not.
   */
  whoItsFor: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  whatYoullBuild?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whatYoullGet?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  timeline?:
    | {
        label: string;
        description?: string | null;
        /**
         * e.g. "Weeks 1–3"
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Which stages this program accepts. Drives filtering and recommendations.
   */
  stage: ('exploring' | 'idea' | 'validation' | 'mvp' | 'early_revenue' | 'scaling' | 'established')[];
  sectors?:
    | (
        | 'ai'
        | 'fintech'
        | 'health'
        | 'climate'
        | 'deeptech'
        | 'saas'
        | 'consumer'
        | 'education'
        | 'hardware'
        | 'agriculture'
        | 'mobility'
        | 'space'
        | 'social_impact'
        | 'media'
        | 'gaming'
      )[]
    | null;
  audience?: ('students' | 'aspiring_founders' | 'founders' | 'researchers' | 'alumni')[] | null;
  format?: ('in_person' | 'hybrid' | 'online') | null;
  /**
   * e.g. "12 weeks"
   */
  duration?: string | null;
  cohortSize?: number | null;
  nextCohortStart?: string | null;
  applicationStatus: 'open' | 'opening_soon' | 'closed' | 'in_progress';
  /**
   * Shown to applicants as both a date and a countdown.
   */
  applicationDeadline?: string | null;
  applicationOpensAt?: string | null;
  /**
   * Mentors attached here appear on this program automatically — no need to re-enter them.
   */
  mentors?: (number | Mentor)[] | null;
  partners?: (number | Partner)[] | null;
  /**
   * Each question gets a stable id when created — reordering or editing later never disconnects it from answers already submitted.
   */
  applicationQuestions?:
    | {
        label: string;
        helpText?: string | null;
        fieldType: 'text' | 'textarea' | 'select' | 'multiselect' | 'url' | 'file';
        /**
         * The choices for a select or multi-select question.
         */
        options?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        required?: boolean | null;
        /**
         * Optional character limit.
         */
        maxLength?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Leave blank to use the title and summary above.
   */
  seo?: {
    /**
     * Around 60 characters.
     */
    title?: string | null;
    /**
     * Around 155 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  heroImage?: (number | null) | Media;
  /**
   * Eligible for the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reviewed before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors".
 */
export interface Mentor {
  id: number;
  name: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  /**
   * e.g. "Co-founder"
   */
  title?: string | null;
  organization?: string | null;
  bio?: string | null;
  /**
   * What founders can come to them for. Drives the "I need help with…" entry.
   */
  expertise: (
    'product' | 'fundraising' | 'gtm' | 'technology' | 'legal' | 'hiring' | 'industry' | 'design' | 'operations'
  )[];
  sectors?:
    | (
        | 'ai'
        | 'fintech'
        | 'health'
        | 'climate'
        | 'deeptech'
        | 'saas'
        | 'consumer'
        | 'education'
        | 'hardware'
        | 'agriculture'
        | 'mobility'
        | 'space'
        | 'social_impact'
        | 'media'
        | 'gaming'
      )[]
    | null;
  availability?: ('open' | 'limited' | 'unavailable') | null;
  linkedinUrl?: string | null;
  photo?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Links this profile to a platform account, mirroring Founders.userId. Without it a signed-in mentor has no way to find their own public profile from the dashboard. Leave blank if they have none.
   */
  userId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for someone who cannot see it. If it is purely decorative, write "decorative".
   */
  alt: string;
  /**
   * Photographer or source, if needed.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  type?: ('industry' | 'academic' | 'government' | 'investor' | 'community') | null;
  description?: string | null;
  websiteUrl?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One run of a program.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts".
 */
export interface Cohort {
  id: number;
  /**
   * e.g. "Spring 2026"
   */
  name: string;
  program: number | Program;
  startsAt?: string | null;
  endsAt?: string | null;
  status?: ('upcoming' | 'in_progress' | 'completed') | null;
  mentors?: (number | Mentor)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public profiles. Nothing private belongs here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "startups".
 */
export interface Startup {
  id: number;
  name: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  tagline: string;
  /**
   * The arc from what was broken to where it stands now. Populate only the stages this startup has actually reached — a startup still at "product" has no honest "progress" entry yet, so leave later stages out rather than filling them with a placeholder.
   */
  story?:
    | {
        stage: 'problem' | 'idea' | 'experiment' | 'product' | 'progress';
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  stage?: ('exploring' | 'idea' | 'validation' | 'mvp' | 'early_revenue' | 'scaling' | 'established') | null;
  sectors?:
    | (
        | 'ai'
        | 'fintech'
        | 'health'
        | 'climate'
        | 'deeptech'
        | 'saas'
        | 'consumer'
        | 'education'
        | 'hardware'
        | 'agriculture'
        | 'mobility'
        | 'space'
        | 'social_impact'
        | 'media'
        | 'gaming'
      )[]
    | null;
  /**
   * Attaching a cohort makes this startup appear on that program automatically.
   */
  cohort?: (number | null) | Cohort;
  founders?: (number | Founder)[] | null;
  /**
   * KIIT school or department.
   */
  school?: string | null;
  foundedYear?: number | null;
  websiteUrl?: string | null;
  /**
   * Only what actually happened. No projections.
   */
  achievements?:
    | {
        label: string;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Optional. Leave blank to use the title and summary above.
   */
  seo?: {
    /**
     * Around 60 characters.
     */
    title?: string | null;
    /**
     * Around 155 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders".
 */
export interface Founder {
  id: number;
  name: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  headline?: string | null;
  bio?: string | null;
  school?: string | null;
  graduationYear?: number | null;
  linkedinUrl?: string | null;
  photo?: (number | null) | Media;
  /**
   * Links this profile to a platform account. Leave blank if they have none.
   */
  userId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startsAt: string;
  endsAt?: string | null;
  eventType?: ('workshop' | 'talk' | 'ideation' | 'demo_day' | 'networking' | 'hackathon' | 'office_hours') | null;
  format?: ('in_person' | 'hybrid' | 'online') | null;
  /**
   * Room or building. Leave blank for online events.
   */
  location?: string | null;
  /**
   * External registration link, if any.
   */
  registrationUrl?: string | null;
  capacity?: number | null;
  /**
   * A KNEST mentor speaking at this event — their bio and photo come from their own profile. Use "Other speakers" below for guests who aren’t in the mentor directory.
   */
  mentorSpeakers?: (number | Mentor)[] | null;
  /**
   * For speakers who don’t have a KNEST mentor profile.
   */
  speakers?:
    | {
        name: string;
        title?: string | null;
        organization?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Used to recommend this event on the right dashboards.
   */
  relevantStages?: ('exploring' | 'idea' | 'validation' | 'mvp' | 'early_revenue' | 'scaling' | 'established')[] | null;
  sectors?:
    | (
        | 'ai'
        | 'fintech'
        | 'health'
        | 'climate'
        | 'deeptech'
        | 'saas'
        | 'consumer'
        | 'education'
        | 'hardware'
        | 'agriculture'
        | 'mobility'
        | 'space'
        | 'social_impact'
        | 'media'
        | 'gaming'
      )[]
    | null;
  program?: (number | null) | Program;
  /**
   * Optional. Ties this event to one specific cohort rather than the program in general — leave blank for a program-wide event.
   */
  cohort?: (number | null) | Cohort;
  heroImage?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Optional. Leave blank to use the title and summary above.
   */
  seo?: {
    /**
     * Around 60 characters.
     */
    title?: string | null;
    /**
     * Around 155 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  summary: string;
  format: 'guide' | 'template' | 'playbook' | 'video' | 'article' | 'worksheet';
  /**
   * Which stages this helps. Drives dashboard recommendations.
   */
  stages: ('exploring' | 'idea' | 'validation' | 'mvp' | 'early_revenue' | 'scaling' | 'established')[];
  topics?:
    | (
        | 'ai'
        | 'fintech'
        | 'health'
        | 'climate'
        | 'deeptech'
        | 'saas'
        | 'consumer'
        | 'education'
        | 'hardware'
        | 'agriculture'
        | 'mobility'
        | 'space'
        | 'social_impact'
        | 'media'
        | 'gaming'
      )[]
    | null;
  /**
   * For resources hosted on KNEST.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For resources hosted elsewhere.
   */
  externalUrl?: string | null;
  /**
   * For downloadable templates.
   */
  file?: (number | null) | Media;
  readingMinutes?: number | null;
  featured?: boolean | null;
  /**
   * Optional. Leave blank to use the title and summary above.
   */
  seo?: {
    /**
     * Around 60 characters.
     */
    title?: string | null;
    /**
     * Around 155 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  author?: string | null;
  /**
   * If this is a founder story.
   */
  startup?: (number | null) | Startup;
  heroImage?: (number | null) | Media;
  /**
   * Optional. Leave blank to use the title and summary above.
   */
  seo?: {
    /**
     * Around 60 characters.
     */
    title?: string | null;
    /**
     * Around 155 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure".
 */
export interface Infrastructure {
  id: number;
  name: string;
  /**
   * The URL for this page. Changing it breaks existing links.
   */
  slug: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  spaceType?:
    | (
        | 'coworking'
        | 'startup_studio'
        | 'collaboration_zone'
        | 'maker_lab'
        | 'digital_studio'
        | 'founder_cabin'
        | 'pre_incubation_space'
        | 'event_space'
        | 'meeting_room'
      )
    | null;
  location?: string | null;
  capacity?: number | null;
  equipment?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  images?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * The person’s name.
   */
  attribution: string;
  /**
   * e.g. "Founder, [startup] · KIIT 2025"
   */
  role?: string | null;
  photo?: (number | null) | Media;
  startup?: (number | null) | Startup;
  program?: (number | null) | Program;
  /**
   * This person has agreed to be quoted publicly, by name.
   */
  consentGiven: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('general' | 'programs' | 'applications' | 'eligibility' | 'mentorship') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only verifiable numbers. Every one needs a date and a source.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics".
 */
export interface Metric {
  id: number;
  /**
   * e.g. "Ventures supported"
   */
  label: string;
  /**
   * e.g. "12" or "₹1.2Cr"
   */
  value: string;
  asOf: string;
  /**
   * Where this number comes from. Internal note — not shown publicly.
   */
  source: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: string;
  email: string;
  name?: string | null;
  staffRole?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'staff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'cohorts';
        value: number | Cohort;
      } | null)
    | ({
        relationTo: 'startups';
        value: number | Startup;
      } | null)
    | ({
        relationTo: 'founders';
        value: number | Founder;
      } | null)
    | ({
        relationTo: 'mentors';
        value: number | Mentor;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'infrastructure';
        value: number | Infrastructure;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'metrics';
        value: number | Metric;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'staff';
        value: string | Staff;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'staff';
    value: string | Staff;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'staff';
    value: string | Staff;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  whoItsFor?: T;
  whatYoullBuild?: T;
  whatYoullGet?: T;
  timeline?:
    | T
    | {
        label?: T;
        description?: T;
        duration?: T;
        id?: T;
      };
  requirements?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  stage?: T;
  sectors?: T;
  audience?: T;
  format?: T;
  duration?: T;
  cohortSize?: T;
  nextCohortStart?: T;
  applicationStatus?: T;
  applicationDeadline?: T;
  applicationOpensAt?: T;
  mentors?: T;
  partners?: T;
  applicationQuestions?:
    | T
    | {
        label?: T;
        helpText?: T;
        fieldType?: T;
        options?:
          | T
          | {
              label?: T;
              id?: T;
            };
        required?: T;
        maxLength?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  heroImage?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts_select".
 */
export interface CohortsSelect<T extends boolean = true> {
  name?: T;
  program?: T;
  startsAt?: T;
  endsAt?: T;
  status?: T;
  mentors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "startups_select".
 */
export interface StartupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  story?:
    | T
    | {
        stage?: T;
        heading?: T;
        body?: T;
        id?: T;
      };
  stage?: T;
  sectors?: T;
  cohort?: T;
  founders?: T;
  school?: T;
  foundedYear?: T;
  websiteUrl?: T;
  achievements?:
    | T
    | {
        label?: T;
        date?: T;
        id?: T;
      };
  logo?: T;
  coverImage?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founders_select".
 */
export interface FoundersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  headline?: T;
  bio?: T;
  school?: T;
  graduationYear?: T;
  linkedinUrl?: T;
  photo?: T;
  userId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors_select".
 */
export interface MentorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  title?: T;
  organization?: T;
  bio?: T;
  expertise?: T;
  sectors?: T;
  availability?: T;
  linkedinUrl?: T;
  photo?: T;
  featured?: T;
  userId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  websiteUrl?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  eventType?: T;
  format?: T;
  location?: T;
  registrationUrl?: T;
  capacity?: T;
  mentorSpeakers?: T;
  speakers?:
    | T
    | {
        name?: T;
        title?: T;
        organization?: T;
        photo?: T;
        id?: T;
      };
  relevantStages?: T;
  sectors?: T;
  program?: T;
  cohort?: T;
  heroImage?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  format?: T;
  stages?: T;
  topics?: T;
  body?: T;
  externalUrl?: T;
  file?: T;
  readingMinutes?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  publishedAt?: T;
  author?: T;
  startup?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure_select".
 */
export interface InfrastructureSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  description?: T;
  spaceType?: T;
  location?: T;
  capacity?: T;
  equipment?:
    | T
    | {
        item?: T;
        id?: T;
      };
  images?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  role?: T;
  photo?: T;
  startup?: T;
  program?: T;
  consentGiven?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics_select".
 */
export interface MetricsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  asOf?: T;
  source?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  id?: T;
  email?: T;
  name?: T;
  staffRole?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Change the copy, choose what is featured, reorder or hide sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The fixed set of homepage sections.
   */
  sections?:
    | {
        /**
         * Which section this is. Not editable.
         */
        key:
          | 'hero'
          | 'problem'
          | 'person'
          | 'knest'
          | 'journey_selector'
          | 'journey'
          | 'offer'
          | 'ecosystem'
          | 'startups'
          | 'closing';
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  heroHeadline: string;
  heroSubhead: string;
  heroPrimaryCta: string;
  heroSecondaryCta?: string | null;
  /**
   * Optional, sits behind the type at low contrast. The headline must stay readable without it.
   */
  heroMedia?: (number | null) | Media;
  problemHeading?: string | null;
  problemBody?: string | null;
  personHeading?: string | null;
  /**
   * Each is set on its own line — the breaks carry the rhythm.
   */
  personLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  knestHeading?: string | null;
  knestBody?: string | null;
  featuredPrograms?: (number | Program)[] | null;
  featuredStartups?: (number | Startup)[] | null;
  featuredEvents?: (number | Event)[] | null;
  testimonials?: (number | Testimonial)[] | null;
  /**
   * Only published, sourced numbers. Leave empty until there are real ones.
   */
  metrics?: (number | Metric)[] | null;
  closingHeading?: string | null;
  closingBody?: string | null;
  closingCta?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        key?: T;
        enabled?: T;
        id?: T;
      };
  heroHeadline?: T;
  heroSubhead?: T;
  heroPrimaryCta?: T;
  heroSecondaryCta?: T;
  heroMedia?: T;
  problemHeading?: T;
  problemBody?: T;
  personHeading?: T;
  personLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  knestHeading?: T;
  knestBody?: T;
  featuredPrograms?: T;
  featuredStartups?: T;
  featuredEvents?: T;
  testimonials?: T;
  metrics?: T;
  closingHeading?: T;
  closingBody?: T;
  closingCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}