'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button, Select, Textarea } from '@/components/ui'

const MIN_PURPOSE = 20

export type DaySlots = {
  key: string
  label: string
  slots: { startsAt: string; label: string; taken: boolean }[]
}

/**
 * Picking a slot and saying what it is for.
 *
 * The slots are handed down from the server, generated by the same
 * `slotsForDay` that validates the submission, so this component never
 * reasons about opening hours. It picks from a list.
 *
 * A taken slot is shown and disabled rather than hidden — "09:00 is gone" is
 * more useful than a gap where 09:00 used to be, and it tells a founder the
 * lab is actually used.
 */
export function BookingForm({
  labId,
  labName,
  slotMinutes,
  maxSlots,
  canExtend,
  days,
}: {
  labId: number
  labName: string
  slotMinutes: number
  maxSlots: number
  canExtend: boolean
  days: DaySlots[]
}) {
  const router = useRouter()
  const [dayKey, setDayKey] = useState(days[0]?.key ?? '')
  const [startsAt, setStartsAt] = useState<string | null>(null)
  const [slots, setSlots] = useState(1)
  const [purpose, setPurpose] = useState('')
  const [pending, setPending] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [done, setDone] = useState(false)

  const day = days.find((entry) => entry.key === dayKey) ?? days[0]
  const short = purpose.trim().length < MIN_PURPOSE

  async function submit(event: React.FormEvent) {
    event.preventDefault()
    if (!startsAt) {
      setError('Pick a slot first.')
      return
    }

    setPending(true)
    setError(null)
    const response = await fetch('/api/labs/bookings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ labId, startsAt, slots, purpose: purpose.trim() }),
    })
    setPending(false)

    if (!response.ok) {
      const data = await response.json().catch(() => null)
      setError(data?.error ?? 'Something went wrong.')
      return
    }
    setDone(true)
    setStartsAt(null)
    setPurpose('')
    router.refresh()
  }

  if (done) {
    return (
      <div className="rounded-[var(--radius-md)] border border-[var(--color-line)] p-6">
        <p className="font-medium">Asked.</p>
        <p className="mt-2 max-w-[60ch] text-[var(--color-ink-soft)]">
          {labName}’s managers have it. They’ll answer, and you’ll get a notification either way —
          it’ll show on your labs page.
        </p>
        <Button className="mt-4" variant="secondary" onClick={() => setDone(false)}>
          Ask for another slot
        </Button>
      </div>
    )
  }

  return (
    <form onSubmit={submit} className="flex flex-col gap-6">
      <label className="flex max-w-[320px] flex-col gap-1.5">
        <span className="text-[length:var(--text-small)] font-medium">Day</span>
        <Select
          value={dayKey}
          onChange={(event) => {
            setDayKey(event.target.value)
            setStartsAt(null)
          }}
        >
          {days.map((entry) => (
            <option key={entry.key} value={entry.key}>
              {entry.label}
            </option>
          ))}
        </Select>
      </label>

      <fieldset>
        <legend className="text-[length:var(--text-small)] font-medium">
          Slot <span className="text-[var(--color-ink-muted)]">— campus time (IST)</span>
        </legend>
        <div className="mt-3 flex flex-wrap gap-2">
          {day?.slots.map((slot) => (
            <button
              key={slot.startsAt}
              type="button"
              disabled={slot.taken}
              aria-pressed={startsAt === slot.startsAt}
              onClick={() => setStartsAt(slot.startsAt)}
              className={`flex h-11 items-center rounded-[var(--radius-sm)] border px-4 text-[length:var(--text-small)] disabled:cursor-not-allowed disabled:opacity-50 ${
                startsAt === slot.startsAt
                  ? 'border-[var(--color-ink)] bg-[var(--color-ink)] text-white'
                  : 'border-[var(--color-line)]'
              }`}
            >
              {slot.label}
              {slot.taken && <span className="ml-2 text-[var(--color-ink-muted)]">taken</span>}
            </button>
          ))}
        </div>
      </fieldset>

      {canExtend && (
        <label className="flex max-w-[320px] flex-col gap-1.5">
          <span className="text-[length:var(--text-small)] font-medium">How long</span>
          <Select value={String(slots)} onChange={(event) => setSlots(Number(event.target.value))}>
            {Array.from({ length: maxSlots }, (_, index) => index + 1).map((count) => (
              <option key={count} value={count}>
                {count === 1 ? `One slot · ${slotMinutes} min` : `${count} slots · ${count * slotMinutes} min`}
              </option>
            ))}
          </Select>
          <span className="text-[length:var(--text-small)] text-[var(--color-ink-muted)]">
            Consecutive slots, unlocked at level 4.
          </span>
        </label>
      )}

      <label className="flex flex-col gap-1.5">
        <span className="text-[length:var(--text-small)] font-medium">What do you need it for?</span>
        <Textarea
          value={purpose}
          onChange={(event) => setPurpose(event.target.value)}
          rows={4}
          placeholder="The manager approving this may not know you. What are you doing, and what will you use?"
        />
      </label>

      <div>
        <Button type="submit" disabled={pending || short || !startsAt}>
          {pending ? 'Asking…' : 'Ask for this slot'}
        </Button>
        <p className="mt-3 max-w-[60ch] text-[length:var(--text-small)] text-[var(--color-ink-muted)]">
          This is a request, not a confirmed booking. {labName}’s managers decide.
        </p>
      </div>

      {error && (
        <p role="alert" className="text-[length:var(--text-small)] text-[var(--color-critical)]">
          {error}
        </p>
      )}
    </form>
  )
}
